#!/usr/bin/env python3
"""Resolve the selected Workshop items into Project Zomboid server settings."""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path


def load_catalog(path: Path) -> dict[str, object]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ValueError(f"Catalog is missing: {path}. Run task mods:discover first.")


def load_selection(path: Path) -> dict[str, object]:
    try:
        selection = tomllib.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ValueError(f"Selection is missing: {path}")

    settings = selection.get("selection")
    if not isinstance(settings, dict):
        raise ValueError(f"[selection] is missing from {path}")

    mode = settings.get("mode")
    if mode not in {"all", "explicit"}:
        raise ValueError("selection.mode must be either 'all' or 'explicit'")

    for key in ("include", "exclude"):
        if not isinstance(settings.get(key, []), list) or not all(
            isinstance(item_id, str) for item_id in settings.get(key, [])
        ):
            raise ValueError(f"selection.{key} must contain Workshop IDs as strings")
    return settings


def resolve(catalog: dict[str, object], selection: dict[str, object]) -> dict[str, object]:
    items = dict(catalog["items"])
    installed_items = {
        item_id: item
        for item_id, item in items.items()
        if bool(item["installed"]) and item["mods"]
    }
    mode = str(selection["mode"])
    include = set(selection.get("include", []))
    exclude = set(selection.get("exclude", []))

    unknown = sorted((include | exclude) - set(items))
    if unknown:
        raise ValueError(f"Unknown Workshop IDs in mods/enabled.toml: {', '.join(unknown)}")

    if mode == "all":
        selected_item_ids = set(installed_items)
    else:
        selected_item_ids = include

    selected_item_ids -= exclude
    missing = sorted(selected_item_ids - set(installed_items))
    if missing:
        raise ValueError(
            "Selected Workshop items are missing locally or do not contain mod.info: "
            + ", ".join(missing)
        )

    mod_index: dict[str, tuple[str, dict[str, object]]] = {}
    duplicates: set[str] = set()
    for item_id, raw_item in installed_items.items():
        for raw_mod in raw_item["mods"]:
            mod = dict(raw_mod)
            mod_id = str(mod["id"])
            if mod_id in mod_index and mod_index[mod_id][0] != item_id:
                duplicates.add(mod_id)
            else:
                mod_index[mod_id] = (item_id, mod)

    selected_mod_ids = {
        str(raw_mod["id"])
        for item_id in selected_item_ids
        for raw_mod in installed_items[item_id]["mods"]
    }
    duplicate_selection = sorted(selected_mod_ids & duplicates)
    if duplicate_selection:
        raise ValueError(
            "Duplicate mod IDs must be resolved before activation: "
            + ", ".join(duplicate_selection)
        )

    resolved_mod_ids: list[str] = []
    resolved_item_ids: list[str] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(mod_id: str) -> None:
        if mod_id in visited:
            return
        if mod_id in visiting:
            raise ValueError(f"Circular mod dependency detected at {mod_id}")
        if mod_id not in mod_index:
            raise ValueError(f"Required mod ID is not installed locally: {mod_id}")
        if mod_id in duplicates:
            raise ValueError(f"Required mod ID is duplicated locally: {mod_id}")

        visiting.add(mod_id)
        item_id, mod = mod_index[mod_id]
        for dependency in mod["requires"]:
            visit(str(dependency))
        visiting.remove(mod_id)
        visited.add(mod_id)
        resolved_mod_ids.append(mod_id)
        if item_id not in resolved_item_ids:
            resolved_item_ids.append(item_id)

    for mod_id in sorted(selected_mod_ids):
        visit(mod_id)

    resolved_items = [
        {
            "id": item_id,
            "url": items[item_id]["url"],
            "mods": [
                mod_id
                for mod_id in resolved_mod_ids
                if mod_index[mod_id][0] == item_id
            ],
        }
        for item_id in resolved_item_ids
    ]
    return {
        "schema_version": 1,
        "workshop_items": resolved_item_ids,
        "mods": resolved_mod_ids,
        "items": resolved_items,
    }


def write_env(path: Path, resolved: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by task mods:generate. Do not edit manually.\n"
        f"PZ_WORKSHOP_ITEMS={';'.join(resolved['workshop_items'])}\n"
        f"PZ_MODS={';'.join(resolved['mods'])}\n",
        encoding="utf-8",
    )


def show(resolved: dict[str, object]) -> None:
    print(f"Workshop items: {len(resolved['workshop_items'])}")
    print(f"Mod IDs: {len(resolved['mods'])}")
    for item in resolved["items"]:
        print(f"{item['id']} {item['url']}")
        print(f"  Mods: {', '.join(item['mods'])}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, default=Path("mods/catalog.lock.json"))
    parser.add_argument("--selection", type=Path, default=Path("mods/enabled.toml"))
    parser.add_argument("--env-output", type=Path, default=Path("mods/resolved.env"))
    parser.add_argument("--json-output", type=Path, default=Path("mods/resolved.json"))
    parser.add_argument("--show", action="store_true")
    args = parser.parse_args()

    try:
        resolved = resolve(load_catalog(args.catalog), load_selection(args.selection))
    except (ValueError, tomllib.TOMLDecodeError) as error:
        print(error, file=sys.stderr)
        return 1

    write_env(args.env_output, resolved)
    args.json_output.write_text(
        json.dumps(resolved, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    if args.show:
        show(resolved)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
